# name of the workflow
name: Integration Workflow

# event that triggers the workflow
on: [push]

jobs:
  build: # name of the job
    runs-on: ubuntu-latest # specify the runner environment
    steps:
      - name: build artifact # name of the step
        run: echo "Hello, GitHub Actions!"
          
  scan: # name of the job
    needs: build
    runs-on: ubuntu-latest # specify the runner environment
    steps:
      - name: scan artifact # name of the step
        run: echo "Bye, GitHub Actions!"
  