# name of the workflow
name: Echo Workflow

# event that triggers the workflow
on: [push]

jobs:
  echo: # name of the job
    runs-on: ubuntu-latest # specify the runner environment
    steps:
      - name: Echo Message
        run: echo "Hello, GitHub Actions!"
      - name: Echo Message
        run: echo "Bye, GitHub Actions!"